In [1]:
import torch
from torch.nn.functional import mse_loss

from sgd_factorise import sgd_factorise, sgd_factorise_masked

# Task 1.2

In [2]:
A = torch.tensor([[0.3374, 0.6005, 0.1735], [3.3359, 0.0492, 1.8374], [2.9407, 0.5301, 2.2620]])
U, V = sgd_factorise(A, 2)
loss = mse_loss(A, U@V.T, reduction='sum')
print(f'MSE Loss: {loss}')

MSE Loss: 0.12194402515888214


In [3]:
print(U)
print(V)

tensor([[ 0.6356, -0.1783],
        [ 0.3861,  1.5653],
        [ 1.0763,  1.1266]])
tensor([[ 0.8717,  1.8626],
        [ 0.7599, -0.1943],
        [ 0.8606,  1.0481]])


# Task 2.1

In [4]:
U2, S2, V2 = torch.svd(A)
print(U2, S2, V2)

tensor([[-0.0801, -0.7448,  0.6625],
        [-0.7103,  0.5090,  0.4863],
        [-0.6994, -0.4316, -0.5697]]) tensor([5.3339, 0.6959, 0.3492]) tensor([[-0.8349,  0.2548,  0.4879],
        [-0.0851, -0.9355,  0.3430],
        [-0.5439, -0.2448, -0.8027]])


In [5]:
# Set the last singular value to zero
S2[-1] = 0
print(S2)

tensor([5.3339, 0.6959, 0.0000])


In [6]:
# A reconstruction
A2 = U2 @ torch.diag(S2) @ V2.T
print(A2)

tensor([[ 0.2245,  0.5212,  0.3592],
        [ 3.2530, -0.0090,  1.9737],
        [ 3.0378,  0.5983,  2.1023]])


In [7]:
loss2 = mse_loss(A, A2, reduction='sum')
print(f'MSE Loss: {loss2}')

MSE Loss: 0.12191088497638702


# Task 3.2

In [8]:
M = torch.tensor([[1, 1, 1], [0, 1, 1], [1, 0, 1]]) # mask
print(M)

tensor([[1, 1, 1],
        [0, 1, 1],
        [1, 0, 1]])


In [9]:
U3, V3 = sgd_factorise_masked(A, M, 2)

In [10]:
loss3 = mse_loss(A, U3@V3.T, reduction='sum')
print(f'MSE Loss: {loss3}')

MSE Loss: 1.119443416595459
