In [1]:
# OPTIONAL: Load the "autoreload" extension so that code can change
%load_ext autoreload

# OPTIONAL: always reload modules so that as you change code in src, it gets loaded
%autoreload 2

In [2]:
import torch
from torch.nn.functional import mse_loss

from sgd_factorise import sgd_factorise, sgd_factorise_masked
torch.manual_seed(0)

# Task 1.2

In [3]:
A = torch.tensor([[0.3374, 0.6005, 0.1735], [3.3359, 0.0492, 1.8374], [2.9407, 0.5301, 2.2620]])
U, V = sgd_factorise(A, 2)
loss = mse_loss(A, U@V.T, reduction='sum')
print(f'MSE Loss: {loss}')

MSE Loss: 0.12197002023458481


In [4]:
print(U)
print(V)

tensor([[ 0.6168, -0.1530],
        [ 0.4108,  1.5961],
        [ 1.0798,  1.1800]])
tensor([[ 0.8126,  1.8290],
        [ 0.7836, -0.2088],
        [ 0.8384,  1.0195]])


# Task 2.1

In [5]:
U2, S2, V2 = torch.svd(A)
print(U2, '\n', S2, '\n', V2)

tensor([[-0.0801, -0.7448,  0.6625],
        [-0.7103,  0.5090,  0.4863],
        [-0.6994, -0.4316, -0.5697]]) 
 tensor([5.3339, 0.6959, 0.3492]) 
 tensor([[-0.8349,  0.2548,  0.4879],
        [-0.0851, -0.9355,  0.3430],
        [-0.5439, -0.2448, -0.8027]])


In [6]:
# Set the last singular value to zero
S2[-1] = 0
print(S2)

tensor([5.3339, 0.6959, 0.0000])


In [7]:
# A reconstruction
A2 = U2 @ torch.diag(S2) @ V2.T
print(A2)

tensor([[ 0.2245,  0.5212,  0.3592],
        [ 3.2530, -0.0090,  1.9737],
        [ 3.0378,  0.5983,  2.1023]])


In [8]:
loss2 = mse_loss(A, A2, reduction='sum')
print(f'MSE Loss: {loss2}')

MSE Loss: 0.12191088497638702


# Task 3.2

In [9]:
M = torch.tensor([[1, 1, 1], [0, 1, 1], [1, 0, 1]]) # mask
print(M)

tensor([[1, 1, 1],
        [0, 1, 1],
        [1, 0, 1]])


In [10]:
U3, V3 = sgd_factorise_masked(A, M, 2)

In [11]:
U3

tensor([[ 0.6501, -0.1515],
        [ 0.2346,  1.2954],
        [ 1.1472,  1.2511]])

In [12]:
V3

tensor([[ 0.9019,  1.5197],
        [ 0.8868, -0.1223],
        [ 0.5406,  1.3175]])

In [13]:
loss3 = mse_loss(A, U3@V3.T, reduction='sum')
print(f'MSE Loss: {loss3}')

MSE Loss: 1.4483590126037598


In [15]:
U3 @ V3.T

tensor([[0.3561, 0.5951, 0.1518],
        [2.1802, 0.0496, 1.8334],
        [2.9360, 0.8643, 2.2685]])